server:
  port: 19081
knife4j:
  enableAggregation: true
  cloud:
    enable: true
    routes:
      - name: 用户体系
        uri: 192.168.0.152:8999
        location: /v2/api-docs?group=2.X版本
        swaggerVersion: 2.0
        servicePath: /abbb/ffe
    routeAuth:
      enable: true
      username: test
      password: 12313
  eureka:
    enable: false
    serviceUrl: http://localhost:10000/eureka/
    routes:
      - name: 订单服务
        serviceName: service-order
        location: /v2/api-docs?group=default
        swaggerVersion: 2.0
        servicePath: /order
      - name: 用户服务
        serviceName: service-user
        location: /aub/v2/api-docs?group=default
        swaggerVersion: 2.0
        servicePath: /user
  disk:
    enable: false
    routes:
      - name: 用户
        location: classpath:openapi/user.json