server:
  port: 18568
spring:
  application:
    name: knife4j-springfox-boot-v3
knife4j:
  enable: true
  documents:
    -
      group: 1.2.x
      name: 测试自定义标题分组
      locations: classpath:md/*
  setting:
    enableSwaggerModels: true
