server:
  port: 8999
  servlet:
    context-path: /cc
spring:
  application:
    name: Knife4j-Demo

logging:
  config: classpath:logback-spring.xml
knife4j:
  enable: true
  documents:
    -
      group: 2.X版本
      name: 接口签名
      locations: classpath:sign/sign1.md
    -
      group: 2.X版本
      name: 另外文档分组请看这里
      locations: classpath:markdown/*
    -
      group: 3.默认接口
      name: 我是另外一个分组的文档
      locations: classpath:markdown/*
  setting:
    language: zh-CN
    enableSwaggerModels: true
    enableDocumentManage: true
    swaggerModelName: 实体类列表
    enableVersion: false
    enableReloadCacheParameter: false
    enableAfterScript: true