server:
  port: 8999
spring:
  application:
    name: SwaggerBootstrapUi-Demo
knife4j:
  enable: false
  markdowns: classpath:markdown/*
  basic:
    enable: false
    username: zhangsan
    password: 123456
logging:
  config: classpath:logback-spring.xml
