server:
  port: 8999
spring:
  application:
    name: Knife4j-Demo
knife4j:
  enable: true
  markdowns: classpath:markdown2x/*
  basic:
    enable: false
    username: zhangsan
    password: 123456
logging:
  config: classpath:logback-spring.xml
