server:
  port: 10001
  servlet:
    context-path: /
spring:
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.223:8848
        username: nacos
        password: nacos
